apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
        software: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
